
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 12 02:11:22 PDT 2004
//----------------------------------------------------

package edu.berkeley.cs.db.yfilterplus.queryparser.xpathparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NCNAME = 24;
  public static final int UNDERSCORE = 8;
  public static final int fn_text = 3;
  public static final int GREATER_THAN = 19;
  public static final int STAR = 4;
  public static final int SLASH = 5;
  public static final int AT = 9;
  public static final int LITERAL = 15;
  public static final int GREATER_THAN_EQUALS = 21;
  public static final int L_PAREN = 11;
  public static final int LETTER = 23;
  public static final int L_BRACKET = 6;
  public static final int NCNAMECHAR = 22;
  public static final int EQUALS = 16;
  public static final int R_PAREN = 12;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int DOUBLE_SLASH = 13;
  public static final int LESS_THAN = 18;
  public static final int NOT_EQUALS = 17;
  public static final int error = 1;
  public static final int DOT = 10;
  public static final int LESS_THAN_EQUALS = 20;
  public static final int R_BRACKET = 7;
  public static final int fn_position = 2;
}

